version: "2"

services:
  mariadb:
    image: centos/mariadb
    ports:
      - "$DB_PORT"
    environment:
      MYSQL_ROOT_PASSWORD: $ROOT_PASS
      MYSQL_DATABASE: $DB_NAME
      MYSQL_PASSWORD: $DB_PASS
      MYSQL_USER: $DB_USER

  wordpress:
    image: wordpress
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    restart: always
    environment:
      WORDPRESS_DB_HOST: $DB_HOST:$DB_PORT
      WORDPRESS_DB_NAME: $DB_NAME
      WORDPRESS_DB_PASSWORD: $DB_PASS
      WORDPRESS_DB_USER: $DB_USER
